# Generated by Django 5.2 on 2026-08-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_variantes_campanas_cupones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('B', 'Boleta'), ('F', 'Factura')], default='B', max_length=1)),
                ('nro_documento', models.CharField(max_length=30)),
                ('fecha_compra', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True)),
                ('aplicado_a_inventario', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles', to='web.compra')),
                ('variante_talla', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='web.variantetalla')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='web.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(fields=('proveedor', 'nro_documento'), name='unico_doc_por_proveedor'),
        ),
    ]
