# Generated by Django 5.2 on 2026-08-25 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_proveedor_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='No registres lineas con cantidad 0: simplemente no incluyas esa talla en la boleta.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
