# Generated by Django 5.2 on 2026-08-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_compradetalle_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantetalla',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventario'},
        ),
    ]
