# Generated by Django 5.2 on 2026-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Codigo #RRGGBB para el circulo en la tienda. Si lo dejas vacio se deduce del nombre.', max_length=7, verbose_name='Color (hex)'),
        ),
    ]
