# Generated by Django 5.2 on 2026-08-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_atributos_curvas_genero'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventario',
            name='unico_valor_por_variante',
        ),
        migrations.RemoveConstraint(
            model_name='inventario',
            name='unica_fila_sin_valor',
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('variante', 'valor'), name='unico_valor_por_variante'),
        ),
    ]
