# Generated by Django 5.2 on 2026-08-26 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_constraint_inventario_mysql'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curva',
            options={'ordering': ['atributo', 'nombre'], 'verbose_name': 'Curva de valores', 'verbose_name_plural': 'Curvas de valores'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='usa_genero',
            field=models.BooleanField(default=False, help_text='Marcar solo en moda (calzado, ropa). En tecnologia o electrodomesticos no aplica.', verbose_name='Usa genero'),
        ),
        migrations.AddField(
            model_name='curva',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Dejar vacio para que sirva en cualquier categoria que use este atributo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curvas', to='web.categoria'),
        ),
        migrations.AddField(
            model_name='curva',
            name='genero',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('N', 'Nino'), ('A', 'Nina'), ('U', 'Unisex')], help_text='Dejar vacio para que sirva en cualquier genero (ej. tallas S-XXL de ropa).', max_length=1),
        ),
    ]
