# Generated by Django 5.2 on 2026-08-26 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_paleta_de_colores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('0', 'Solicitado'), ('1', 'Pagado'), ('2', 'Enviado'), ('3', 'Entregado'), ('4', 'Cancelado')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Saldo inicial'), ('COMPRA', 'Compra'), ('ANULA_COMPRA', 'Anulacion de compra'), ('VENTA', 'Venta'), ('CANCELA_VENTA', 'Cancelacion de venta'), ('AJUSTE', 'Ajuste manual')], max_length=15)),
                ('cantidad', models.IntegerField(help_text='Positiva si entra, negativa si sale.')),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_resultante', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('costo_promedio_resultante', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='web.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='web.inventario')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='web.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Kardex',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['item', '-fecha'], name='idx_kardex_item_fecha')],
            },
        ),
    ]
