# Generated by Django 5.2 on 2026-08-26 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_saldo_inicial_kardex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaRecaudadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('BANCO', 'Transferencia o deposito'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('QR', 'Codigo QR')], max_length=10)),
                ('titular', models.CharField(help_text='A nombre de quien esta la cuenta.', max_length=120)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dolares')], default='PEN', max_length=3)),
                ('banco', models.CharField(blank=True, help_text='BCP, Interbank, BBVA...', max_length=40)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=10)),
                ('numero', models.CharField(blank=True, max_length=25)),
                ('cci', models.CharField(blank=True, help_text='Codigo interbancario, para que le transfieran desde otro banco.', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('imagen_qr', models.ImageField(blank=True, upload_to='cuentas')),
                ('instrucciones', models.CharField(blank=True, help_text='Una linea extra que se muestra al cliente. Opcional.', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor primero en el checkout.')),
            ],
            options={
                'verbose_name': 'Cuenta de recaudacion',
                'verbose_name_plural': 'Cuentas de recaudacion',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('0', 'Solicitado'), ('5', 'En validacion'), ('1', 'Pagado'), ('2', 'Enviado'), ('3', 'Entregado'), ('4', 'Cancelado')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_declarado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nro_operacion', models.CharField(help_text='El numero que genera el banco o Yape al transferir.', max_length=40)),
                ('voucher', models.ImageField(upload_to='vouchers/%Y/%m')),
                ('fecha_pago', models.DateField(help_text='La fecha que figura en el comprobante.')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('V', 'Validado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('monto_confirmado', models.DecimalField(blank=True, decimal_places=2, help_text='El monto que viste en tu cuenta. No el que declaro el cliente.', max_digits=10, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='web.cuentarecaudadora')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos', to='web.pedido')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'constraints': [models.UniqueConstraint(fields=('cuenta', 'nro_operacion'), name='unica_operacion_por_cuenta')],
            },
        ),
    ]
