# Generated by Django 5.2 on 2026-08-26 07:06

import web.models.pagos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_cuentas_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='voucher',
            field=models.ImageField(storage=web.models.pagos.AlmacenPrivado(), upload_to='vouchers/%Y/%m'),
        ),
    ]
