# Generated by Django 5.2 on 2026-08-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_voucher_fuera_de_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='reservado',
            field=models.PositiveIntegerField(default=0, help_text='Comprometido por pedidos sin pagar. Sigue en el estante, pero no se vende.'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fuera_de_plazo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='reserva_vence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Lo que hay en el estante, este prometido o no.'),
        ),
    ]
