# Generated by Django 5.2 on 2026-08-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_pedidos_abiertos_a_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoRecojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=60)),
                ('provincia', models.CharField(help_text='La ciudad. De aca sale el traslado entre ciudades.', max_length=60)),
                ('departamento', models.CharField(default='Huancavelica', max_length=60)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('horario', models.CharField(blank=True, help_text='Ej. Lun a Sab de 9:00 a 19:00', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor primero en el checkout.')),
            ],
            options={
                'verbose_name': 'Punto de recojo',
                'verbose_name_plural': 'Puntos de recojo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='modo_entrega',
            field=models.CharField(choices=[('E', 'Envio a domicilio'), ('R', 'Recojo en tienda')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='punto_recojo_direccion',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='pedido',
            name='punto_recojo_nombre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='departamento_envio',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='distrito_envio',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('0', 'Solicitado'), ('5', 'En validacion'), ('1', 'Pagado'), ('2', 'Enviado'), ('6', 'Listo para recojo'), ('3', 'Entregado'), ('4', 'Cancelado')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='provincia_envio',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pedido',
            name='punto_recojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='web.puntorecojo'),
        ),
    ]
