# Generated by Django 5.2 on 2026-08-27 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_puntos_de_recojo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('es_principal', models.BooleanField(default=False, help_text='El almacen general, donde entra lo que se compra.')),
                ('dia_despacho', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], default=5, help_text='Que dia sale la mercaderia hacia aca.')),
                ('dias_viaje', models.PositiveSmallIntegerField(default=2, help_text='Cuantos dias tarda en estar disponible desde que sale.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='trasladable',
            field=models.BooleanField(default=True, help_text='Si los productos de esta categoria pueden viajar entre ciudades. Una refrigeradora cuesta mas trasladarla que lo que deja la venta.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='trasladable',
            field=models.BooleanField(blank=True, help_text='Vacio = como su categoria. Solo para la excepcion puntual: un microondas chico que si viaja, un producto fragil que no.', null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('INICIAL', 'Saldo inicial'), ('COMPRA', 'Compra'), ('ANULA_COMPRA', 'Anulacion de compra'), ('VENTA', 'Venta'), ('CANCELA_VENTA', 'Cancelacion de venta'), ('TRASLADO_SAL', 'Traslado: salida'), ('TRASLADO_ENT', 'Traslado: entrada'), ('AJUSTE', 'Ajuste manual')], max_length=15),
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateField(help_text='Cuando sale la mercaderia.')),
                ('fecha_disponible', models.DateField(help_text='Cuando queda disponible en destino. Es la fecha que ve el cliente.')),
                ('estado', models.CharField(choices=[('P', 'Planificado'), ('T', 'En transito'), ('R', 'Recibido'), ('A', 'Anulado')], default='P', max_length=1)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('despachado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_despachados', to=settings.AUTH_USER_MODEL)),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_recibidos', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_recibidos', to='web.ubicacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_enviados', to='web.ubicacion')),
            ],
            options={
                'verbose_name': 'Traslado',
                'verbose_name_plural': 'Traslados',
                'ordering': ['-fecha_despacho', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='traslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='web.traslado'),
        ),
        migrations.CreateModel(
            name='TrasladoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('motivo', models.CharField(choices=[('P', 'Por pedido'), ('S', 'Por stock')], default='S', max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_salida', to='web.inventario')),
                ('item_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='traslados_entrada', to='web.inventario')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados', to='web.pedido')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalles', to='web.traslado')),
            ],
            options={
                'ordering': ['motivo', 'id'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.ForeignKey(help_text='En que ciudad esta fisicamente esta mercaderia.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='web.ubicacion'),
        ),
    ]
