# Generated by Django 5.2 on 2026-08-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_ubicacion_obligatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntorecojo',
            name='ubicacion',
            field=models.ForeignKey(help_text='De que almacen se sirve este mostrador.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='puntos', to='web.ubicacion'),
        ),
    ]
