# Generated by Django 5.2 on 2026-08-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_numero_de_pedido_al_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_checkout',
            field=models.CharField(blank=True, editable=False, help_text='Identifica el envio del formulario, para no duplicar el pedido.', max_length=32, null=True, unique=True),
        ),
    ]
