# Generated by Django 5.2 on 2026-08-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_estado_expirado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fuera_de_plazo',
        ),
    ]
