"""
Django settings for goatsystem project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--k5%1eelhwb&yvf2nem(0ncr!&6t19r5)i)6up81+94u+_)*6#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Aplicaciones agregadas
    'web',
    # Aplicaciones predeterminadas
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'goatsystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goatsystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "db_goat",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

# Archivos que NUNCA se sirven por URL. Todo lo que esta bajo MEDIA_ROOT lo
# entrega Django en desarrollo y Nginx en produccion a cualquiera que adivine la
# ruta, sin pasar por ningun permiso. Los comprobantes de pago llevan datos
# bancarios del cliente, asi que viven aca y solo salen por una vista que revisa
# quien esta pidiendo.
PRIVADO_ROOT = os.path.join(BASE_DIR, 'privado')

# Cuanto le guardamos el producto al cliente mientras va a pagar.
# Corto de mas es peor que largo de mas: si vence a mitad de la transferencia,
# el cliente ya movio plata y hay que devolversela. Contar lo que tiene que
# hacer -- abrir Yape, escanear, confirmar, sacar captura, volver y subirla --
# son 4 o 5 minutos para alguien agil, y 10 con transferencia bancaria.
MINUTOS_RESERVA = 15

# Lo que le prometemos al cliente: en cuanto confirmamos su pago.
#
# Este plazo NO es simetrico con el de arriba, y es a proposito. Los 15 minutos
# son plazo del cliente: todavia no pago, y si no cumple soltamos la unidad sin
# que le cueste nada. Estas horas son plazo NUESTRO: el cliente ya transfirio,
# ya hizo su parte, y soltarle la unidad seria castigarlo por nuestra demora.
# Por eso el de despues es mas largo: no es una fecha limite para el, es una red
# por si nos trabamos.
HORAS_VALIDACION = 12

# Y a las cuantas horas la bandeja lo marca como demorado. Es la alarma interna,
# la mitad del plazo prometido, para llegar a tiempo y no enterarse tarde.
HORAS_ALERTA_VALIDACION = 6

# A quien se le avisa cuando llega un comprobante. En desarrollo el correo sale
# por consola; el SMTP real se configura en la fase 8, que igual hace falta para
# escribirle al cliente.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'GOAT X <no-responder@goatx.pe>'
CORREOS_AVISO = ['deybis.cc@hotmail.com']
