"""
Django settings for goatsystem project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--k5%1eelhwb&yvf2nem(0ncr!&6t19r5)i)6up81+94u+_)*6#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Aplicaciones agregadas
    'web',
    # Aplicaciones predeterminadas
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middleware.VencerReservasMiddleware',
]

ROOT_URLCONF = 'goatsystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goatsystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "db_goat",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

# Archivos que NUNCA se sirven por URL. Todo lo que esta bajo MEDIA_ROOT lo
# entrega Django en desarrollo y Nginx en produccion a cualquiera que adivine la
# ruta, sin pasar por ningun permiso. Los comprobantes de pago llevan datos
# bancarios del cliente, asi que viven aca y solo salen por una vista que revisa
# quien esta pidiendo.
PRIVADO_ROOT = os.path.join(BASE_DIR, 'privado')

# Cuanto le guardamos el producto al cliente mientras va a pagar.
#
# Es plazo del cliente: todavia no pago. Si no cumple, se suelta la unidad y no
# le costo nada. El que ya transfirio y se paso del plazo no queda afuera: sube
# su comprobante igual, cuando sea, y se resuelve mirandolo.
MINUTOS_RESERVA = 10

# Lo que le prometemos al cliente: en cuanto confirmamos su pago.
#
# Es plazo NUESTRO y por eso NO le quita la unidad a nadie. El cliente ya
# transfirio, ya hizo su parte; soltarle el producto porque nosotros tardamos
# seria castigarlo por nuestra demora. Con el comprobante arriba, la unidad
# queda congelada hasta que una persona decida, tarde lo que tarde.
# Este numero es la promesa que mostramos y avisamos, no un vencimiento.
HORAS_VALIDACION = 12

# Cada cuanto el trafico normal paga el costo de barrer las reservas vencidas.
# No es el plazo de nada: es cada cuanto se revisa si algun plazo se cumplio.
# En 0 se apaga el barrido automatico y queda solo el comando.
SEGUNDOS_ENTRE_BARRIDOS = 60

# Y a las cuantas horas la bandeja lo marca como demorado. Es la alarma interna,
# la mitad del plazo prometido, para llegar a tiempo y no enterarse tarde.
HORAS_ALERTA_VALIDACION = 6

# El asesor que atiende por WhatsApp: devoluciones, dudas y todo lo que no
# resuelve una pantalla. Formato internacional, sin + ni espacios.
WHATSAPP_ASESOR = '51955134139'

# A quien se le avisa cuando llega un comprobante. En desarrollo el correo sale
# por consola; el SMTP real se configura en la fase 8, que igual hace falta para
# escribirle al cliente.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'GOAT X <no-responder@goatx.pe>'
CORREOS_AVISO = ['deybis.cc@hotmail.com']
